version: '3'

services:
  spark:
    image: docker.io/bitnami/spark
    user: root
    networks:
      my_dae_project:
        ipv4_address: 172.1.0.2
    environment:
      - PYTHONIOENCODING=utf8
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8080'
      - '7077:7077'
    volumes:
      - ./src:/opt/bitnami/spark/src

  spark-worker:
    image: docker.io/bitnami/spark
    user: root
    networks:
      my_dae_project:
        ipv4_address: 172.1.0.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./data_csv:/opt/bitnami/spark/src/csvdata

  application_db:
    image: "postgres:13"
    environment:
        POSTGRES_USER: [username]
        POSTGRES_PASSWORD: [password]
        POSTGRES_DB: applicationdb1
    restart: always
    networks:
      my_dae_project:
        ipv4_address: 172.1.0.4
    ports:
        - "5432:5432"
    volumes:
        - ./applicationdb/data:/var/lib/postgresql/data

  data_warehouse:
    image: "postgres:13"
    environment:
        POSTGRES_USER: [username]
        POSTGRES_PASSWORD: [password]
        POSTGRES_DB: datawarehouse1
    restart: always
    networks:
      my_dae_project:
        ipv4_address: 172.1.0.5
    ports:
        - "5431:5432"
    volumes:
        - ./datewarehouse/data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5
    restart: always
    networks:
      my_dae_project:
        ipv4_address: 172.1.0.6
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db

networks:
  my_dae_project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24